### PR TITLE
remove use of `meta = with lib;`

### LINKED ISSUE #414: Nixpkgs style
nix-init adds `with lib;` to the meta section of a derivation, which doesn't align with nixpkgs' style:

https://github.com/NixOS/nixpkgs/pull/291322#discussion_r1503823212

### PR DESCRIPTION
**Pull request by eclairevoyant**
Motivating discussion: NixOS/nixpkgs#208242

Additional context: https://github.com/NixOS/nixpkgs/issues/292468, https://github.com/NixOS/nixpkgs/pull/293767 

Fixes #414.

### CODE REVIEW

**Review by Gerg-L — APPROVED** [review]
LGTM!

**Comment by eclairevoyant** [comment]
@figsoda any feedback on this?

**Comment by figsoda** [comment]
Sorry that I forgot about this for so long. Is there a consensus on this? If not maybe I can create a pole or something like that

**Comment by mweinelt** [comment]
No, there is no consensus on removing it from `meta`. The same people are constantly pushing for it and steamrolling maintainers, and in the latest case my review concerns were simply ignored.

**Comment by eclairevoyant** [comment]
> No, there is no consensus on removing it from `meta`.

True, but I would like to spare contributors who use `nix-init` from getting nitted to death.

I do not see a massive harm in removing `meta = with lib;` from this tool, which IMO is not related to the consensus of removing `meta = with lib;` from nixpkgs.

**Comment by eclairevoyant** [comment]
NB as mentioned in https://github.com/NixOS/nixpkgs/issues/292468#issuecomment-2016454242, `meta = with lib;` has shown itself to be a footgun as well.

**Comment by eclairevoyant** [comment]
@figsoda as mentioned 4 months ago, this is no longer a nit and is actually an issue; any chance to look at this again?

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
